version: "3.7"
services:
  db:
    image:  mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - flasknet

  app:
    image: ankurpatel/flaskapp:latest
    depends_on:
      - db
    ports:
      - "5000:5000"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
    environment:
      - FLASK_ENV=dev
    networks:
      - flasknet
    healthcheck:
      test: curl --fail http://localhost:5000/ping || exit 1
      interval: 10s
      timeout: 2s
      retries: 5

  visualizer:
    image: dockersamples/visualizer:latest
    ports:
      - 8080:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - flasknet

networks:
  flasknet:
    driver: overlay
