version: "3.7"
services:

  db:
    image:  mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
    networks:
      - flasknet

  app:
    image: ankurpatel/flaskapp:latest
    depends_on:
      - db
    ports:
      - "5000:5000"
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
    environment:
      - FLASK_ENV=dev
    networks:
      - flasknet

networks:
  flasknet:
    driver: overlay
