version: "3.6"
services:
  db:
    image:  mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      
      - DB_USER=root
      - DB_PASSWORD=root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]


  app:
    image: ankurpatel/flaskapp:latest
    depends_on:
      - db
    ports:
      - "5000:5000"
